### ISSUE TITLE
Category validation

### ISSUE THREAD

**Issue by joshcosta** [gradebook/server#128]
I think this todo can be removed. If not, we need to address the missing validation cases.

https://github.com/gradebook/server/blob/4f6520b242e21a9cdf62dc175ce34e7e5c7b20a2/lib/controllers/category.js#L60

Validated in [create-category.json](https://github.com/gradebook/server/blob/master/lib/services/validation/schemas/create-category.json) and [create-grade.json](https://github.com/gradebook/server/blob/master/lib/services/validation/schemas/create-grade.json)

**Comment by vikaspotluri123** [comment]
This is already [covered](https://github.com/gradebook/server/projects/1#card-42317945) in the 4.0 project 😁

**Comment by vikaspotluri123** [comment]
Handled by #133
