### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Shlok-Bhakta** [gradebook/server#234]
I love using this, is there any docker container available for deployment to a personal server? If not it would be nice to have one just so I know that all my personal grade data is stored on my hardware.

**Comment by vikaspotluri123** [comment]
@Shlok-Bhakta thanks for reaching out! There isn't a Docker container available since our infrastructure doesn't use Docker.

FYI, we're not able to open-source the frontend at this time, so you might have to play around a bit to get it to work with a self-hosted server.

**Comment by vikaspotluri123** [comment]
@Shlok-Bhakta feel free to reach out if you have any other questions, I'm closing this issue for now 🙂
